import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snb
import mysql.connector 

db = mysql.connector.connect(host = "localhost" , 
                             username = "root" ,
                             password = "Anmol1123@#" , 
                             database = "ecommerce")   #This is used to establish connection with mysql 
cur = db.cursor()

# Query 10 ---> Calculate the total revenue generated by each seller, and rank them by revenue.
print("Query 10--->")
query10 = """ Select * , dense_rank() over (order by revenue desc) 
as Rn from 
(Select order_items.seller_id , sum(payments.payment_value) as revenue from order_items join payments on order_items.order_id = payments.order_id
Group By
order_items.seller_id) as a 
"""
cur.execute (query10)
total_revenue_generated_by_each_seller = cur.fetchall()
df1 = pd.DataFrame(total_revenue_generated_by_each_seller , columns=["Seller_id" ,"Total_Sum" ,"Rn"])
snb.barplot(x = "Seller_id" ,y="Total_Sum" ,data=df1.head()) 
print(df1)
plt.xticks(rotation = 90)
plt.show()

